version: "3.9"
services:
  static:
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: debug
      LOG_PRETTY: "true"
      ENDPOINTS_PATH: /config
    build:
      context: .
    volumes:
      - ./example/endpoints.yaml:/config/endpoints.yaml:ro
