FROM golang:1.25-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o operator ./cmd/operator

FROM scratch
WORKDIR /app
COPY --from=builder /build/operator .

ENTRYPOINT ["./operator"]
