//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *Method) DeepCopyInto(out *Method) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *Method) DeepCopy() *Method {
	if in == nil {
		return nil
	}
	out := new(Method)
	in.DeepCopyInto(out)
	return out
}

func (in *StaticAPI) DeepCopyInto(out *StaticAPI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *StaticAPI) DeepCopy() *StaticAPI {
	if in == nil {
		return nil
	}
	out := new(StaticAPI)
	in.DeepCopyInto(out)
	return out
}

func (in *StaticAPI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *StaticAPIList) DeepCopyInto(out *StaticAPIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StaticAPI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *StaticAPIList) DeepCopy() *StaticAPIList {
	if in == nil {
		return nil
	}
	out := new(StaticAPIList)
	in.DeepCopyInto(out)
	return out
}

func (in *StaticAPIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *StaticAPISpec) DeepCopyInto(out *StaticAPISpec) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]Method, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *StaticAPISpec) DeepCopy() *StaticAPISpec {
	if in == nil {
		return nil
	}
	out := new(StaticAPISpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StaticAPIStatus) DeepCopyInto(out *StaticAPIStatus) {
	*out = *in
}

func (in *StaticAPIStatus) DeepCopy() *StaticAPIStatus {
	if in == nil {
		return nil
	}
	out := new(StaticAPIStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *Static) DeepCopyInto(out *Static) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *Static) DeepCopy() *Static {
	if in == nil {
		return nil
	}
	out := new(Static)
	in.DeepCopyInto(out)
	return out
}

func (in *Static) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *StaticList) DeepCopyInto(out *StaticList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Static, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *StaticList) DeepCopy() *StaticList {
	if in == nil {
		return nil
	}
	out := new(StaticList)
	in.DeepCopyInto(out)
	return out
}

func (in *StaticList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *StaticSpec) DeepCopyInto(out *StaticSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
}

func (in *StaticSpec) DeepCopy() *StaticSpec {
	if in == nil {
		return nil
	}
	out := new(StaticSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StaticStatus) DeepCopyInto(out *StaticStatus) {
	*out = *in
}

func (in *StaticStatus) DeepCopy() *StaticStatus {
	if in == nil {
		return nil
	}
	out := new(StaticStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}
