apiVersion: static.io/v1alpha1
kind: StaticAPI
metadata:
  name: ping
spec:
  path: /ping
  methods:
  - method: GET
    statusCode: 200
    body: 'pong'
    headers:
      content-type: "text/plain"
